### ISSUE TITLE
bugs while using --add_dummy true

### ISSUE THREAD

**Issue by ZhuYun97** [HKUST-KnowComp/DummyNode4GraphLearning#4]
At first, I use such command to download and generate required datasets:
`python data_processing/tu_data_processing.py --dataset PROTEINS --data_dir data_processing/tu_data`.
Then, I use this command to test GIN with a dummy node. 
`python main.py --dataset PROTEINS --dataset_dir ../data_processing/tu_data --model GIN --add_dummy true`

But unfortunately, some bugs happen when I try it.
```
[2022-09-12 16:17:21,401 GIN] Running on dataset PROTEINS
Downloading https://www.chrsmrrs.com/graphkerneldatasets/PROTEINS.zip
Extracting ..\data_processing\tu_data\PROTEINS\PROTEINS.zip
Traceback (most recent call last):
  File "main.py", line 221, in <module>
    dataset = PYGDataset(
  File "C:\Users\zhuyun\Desktop\repos\DummyNode4GraphLearning\graph_classification\graph_neural_networks\dataset.py", line 31, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "C:\Users\zhuyun\anaconda3\lib\site-packages\torch_geometric\data\in_memory_dataset.py", line 60, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "C:\Users\zhuyun\anaconda3\lib\site-packages\torch_geometric\data\dataset.py", line 84, in __init__
    self._download()
  File "C:\Users\zhuyun\anaconda3\lib\site-packages\torch_geometric\data\dataset.py", line 141, in _download
    self.download()
  File "C:\Users\zhuyun\Desktop\repos\DummyNode4GraphLearning\graph_classification\graph_neural_networks\dataset.py", line 116, in download
    raise ValueError("Please use tu_data_processing.py to add_dummy and convert_conjugate")
ValueError: Please use tu_data_processing.py to add_dummy and convert_conjugate
```

**Comment by ZhuYun97** [comment]
Annotating [this  line](https://github.com/HKUST-KnowComp/DummyNode4GraphLearning/blob/master/graph_classification/graph_neural_networks/dataset.py#L116) seems to work. It is better to detect whether the required dataset is already pre-processed. If not, it will incur an error.
